// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'goods.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_goods _$goodsFromJson(Map<String, dynamic> json) => _goods(
  id: (json['id'] as num?)?.toInt(),
  brandId: (json['brandId'] as num?)?.toInt(),
  categoryId: (json['categoryId'] as num?)?.toInt(),
  brandName: json['brandName'] as String?,
  categoryName: json['categoryName'] as String?,
  goodsSn: json['goodsSn'] as String?,
  name: json['name'] as String?,
  gallery: (json['gallery'] as List<dynamic>?)
      ?.map((e) => e as String)
      .toList(),
  keywords: json['keywords'] as String?,
  goodsBrief: json['goodsBrief'] as String?,
  isOnSale: (json['isOnSale'] as num?)?.toInt(),
  sortOrder: (json['sortOrder'] as num?)?.toInt(),
  counterPrice: (json['counterPrice'] as num?)?.toInt(),
  isNewly: json['isNewly'] as bool?,
  primaryPicUrl: json['primaryPicUrl'] as String?,
  listPicUrl: json['listPicUrl'] as String?,
  isHot: (json['isHot'] as num?)?.toInt(),
  goodsUnit: json['goodsUnit'] as String?,
  retailPrice: (json['retailPrice'] as num?)?.toInt(),
  goodsDesc: json['goodsDesc'] as String?,
  attributes: json['attributes'] as String?,
  addTime: (json['addTime'] as num?)?.toInt(),
  status: json['status'] as String?,
  salesNum: (json['salesNum'] as num?)?.toInt(),
  integralper: json['integralper'] as String?,
  homePageFlag: (json['homePageFlag'] as num?)?.toInt(),
  homePageCateCode: (json['homePageCateCode'] as num?)?.toInt(),
  homePageCateDesc: json['homePageCateDesc'] as String?,
  stockNum: (json['stockNum'] as num?)?.toInt(),
  activityFlag: (json['activityFlag'] as num?)?.toInt(),
  activityId: (json['activityId'] as num?)?.toInt(),
  goodsType: (json['goodsType'] as num?)?.toInt(),
  goodsOwnerMobile: json['goodsOwnerMobile'] as String?,
  goodsOwnerId: json['goodsOwnerId'] as String?,
  specificationValue: json['specificationValue'] as String?,
  newProperty: json['newProperty'] as bool?,
);

Map<String, dynamic> _$goodsToJson(_goods instance) => <String, dynamic>{
  'id': instance.id,
  'brandId': instance.brandId,
  'categoryId': instance.categoryId,
  'brandName': instance.brandName,
  'categoryName': instance.categoryName,
  'goodsSn': instance.goodsSn,
  'name': instance.name,
  'gallery': instance.gallery,
  'keywords': instance.keywords,
  'goodsBrief': instance.goodsBrief,
  'isOnSale': instance.isOnSale,
  'sortOrder': instance.sortOrder,
  'counterPrice': instance.counterPrice,
  'isNewly': instance.isNewly,
  'primaryPicUrl': instance.primaryPicUrl,
  'listPicUrl': instance.listPicUrl,
  'isHot': instance.isHot,
  'goodsUnit': instance.goodsUnit,
  'retailPrice': instance.retailPrice,
  'goodsDesc': instance.goodsDesc,
  'attributes': instance.attributes,
  'addTime': instance.addTime,
  'status': instance.status,
  'salesNum': instance.salesNum,
  'integralper': instance.integralper,
  'homePageFlag': instance.homePageFlag,
  'homePageCateCode': instance.homePageCateCode,
  'homePageCateDesc': instance.homePageCateDesc,
  'stockNum': instance.stockNum,
  'activityFlag': instance.activityFlag,
  'activityId': instance.activityId,
  'goodsType': instance.goodsType,
  'goodsOwnerMobile': instance.goodsOwnerMobile,
  'goodsOwnerId': instance.goodsOwnerId,
  'specificationValue': instance.specificationValue,
  'newProperty': instance.newProperty,
};
